version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cs92ib0gph6c73bvi170-a
      DB_PORT: 5432
      DB_DATABASE: clasifieds_pov3
      DB_USERNAME: classifieds_pov3_user
      DB_PASSWORD: M5PtH9lbhCK1H03cjiPJmN8x6ukCKqin
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: >
      sh -c "
        php artisan migrate --force &&
        php artisan db:seed --class=PermissionTableSeeder &&
        php artisan db:seed --class=CategoryTableSeeder &&
        php artisan db:seed --class=SubCategoryTableSeeder &&
        php artisan db:seed --class=CreateAdminUserSeeder &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: clasifieds_pov3
      POSTGRES_USER: classifieds_pov3_user
      POSTGRES_PASSWORD: M5PtH9lbhCK1H03cjiPJmN8x6ukCKqin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
