version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cuvebnaj1k6c73ebsau0-a
      DB_PORT: 5432
      DB_DATABASE: Kaolo Annonce
      DB_USERNAME: kaolo_user
      DB_PASSWORD: 4QE7OyHW8nXVrX1lgsTdPZQqB4WfCWxL
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: >
      sh -c "
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0
      "

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Kaolo Annonce
      POSTGRES_USER: kaolo_user
      POSTGRES_PASSWORD: 4QE7OyHW8nXVrX1lgsTdPZQqB4WfCWxL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
