version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: Kaolo Annonce
      POSTGRES_USER: kaolo_user
      POSTGRES_PASSWORD: 4QE7OyHW8nXVrX1lgsTdPZQqB4WfCWxL
    ports:
      - "5432:5432"
