services:
  - type: web
    name: laravel-app
    env: docker
    docker:
      dockerfile_path: Dockerfile
    plan: free
    build:
      dockerfile_path: Dockerfile
    start_command: ["php-fpm"]
    health_check:
      path: /
      interval: 30s
      timeout: 10s
